### ISSUE TITLE
Compile error - non-boolean condition in if statement

### ISSUE THREAD

**Issue by iobear** [rmasci/sslcheck#3]
Thanks for your simple sslcheck!
I get an compile error, after an "git checkout" of your repo.

#go run .
./main.go:164:5: non-boolean condition in if statement
./main.go:170:5: non-boolean condition in if statement

I think the two bottom if statements, you meant "if verb.v" instead of "if verb" :-)

**Comment by rmasci** [comment]
Hey thanks for the heads up. I fixed this issue, so do a git pull and try compiling again. Should work. You could also use the version in the 'binaries' folder. I build it for linux / mac / windows.
Thanks -- Rich

**Comment by iobear** [comment]
Perfect
